#!/bin/bash

# Auto-push feature branches after commit
branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" != "main" && "$branch" != "master" ]]; then
  git push origin "$branch" 2>/dev/null
fi
